---
# tasks/configure_nginx_proxy.yml
- name: Configure Nginx for Matrix
  template:
    src: nginx_matrix.conf.j2
    dest: /etc/nginx/sites-available/matrix
    owner: root
    group: root
    mode: '0644'
  notify: Reload Nginx

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/matrix
    dest: /etc/nginx/sites-enabled/matrix
    state: link
  notify: Reload Nginx

- name: Disable default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx