---
# tasks/install_synapse.yml
- name: Add Matrix.org repository key
  apt_key:
    url: https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg
    state: present

- name: Add Matrix.org repository
  apt_repository:
    repo: deb https://packages.matrix.org/debian/ {{ ansible_distribution_release }} main
    state: present
    filename: matrix-org

- name: Install Matrix Synapse
  apt:
    name: matrix-synapse
    state: present
    update_cache: yes

- name: Configure Synapse server name
  template:
    src: homeserver.yaml.j2
    dest: /etc/matrix-synapse/homeserver.yaml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Synapse

- name: Start and enable Matrix Synapse
  systemd:
    name: matrix-synapse
    state: started
    enabled: yes